<a href="https://colab.research.google.com/github/mmorra13/Intro-To-ML/blob/main/Homework_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch as torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torchvision
import torchvision.transforms as transforms
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from torch.nn.functional import normalize
import torch.optim as optim
from google.colab import drive
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#PROBLEM 1a
# Load the housing dataset
file_path = '/content/drive/My Drive/Courses/Intro-to-ML/Datasets/Housing.csv'
housing = pd.DataFrame(pd.read_csv(file_path))

In [ ]:
#Convert YES/NO to 1/0
varlist = ['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']

#Defining map function
def binary_map(x):
  return x.map({'yes': 1, 'no': 0})

#Applying the function to the housing list
housing[varlist] = housing[varlist].apply(binary_map)

#Ignore furnishing status
housing = housing.drop('furnishingstatus', axis=1)

#Extract output
Y1 = housing['price'].values

#Extract inputs
housing = housing.drop('price', axis=1)
X1 = housing.values

#Split the dataset
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1,Y1, test_size = 0.8, random_state = 0)

#Input standardization
sc = StandardScaler()
X1_train = sc.fit_transform(X1_train)
X1_test = sc.transform(X1_test)

#Ouptut standardization
Y1_train = sc.fit_transform(Y1_train.reshape(-1,1)).flatten()
Y1_test = sc.fit_transform(Y1_test.reshape(-1,1)).flatten()

#Conver to tensors
X1_train_ten = torch.tensor(X1_train, dtype=torch.float32)
X1_test_ten = torch.tensor(X1_test, dtype=torch.float32)
Y1_train_ten = torch.tensor(Y1_train, dtype=torch.float32)
Y1_test_ten = torch.tensor(Y1_test, dtype=torch.float32)

#Dataloader for training and test sets
train_dataset = TensorDataset(X1_train_ten, Y1_train_ten)
train_loader = DataLoader(train_dataset, batch_size = 32, shuffle=True)

test_dataset = TensorDataset(X1_test_ten, Y1_test_ten)
test_loader = DataLoader(test_dataset, batch_size = 32)

In [ ]:
#Define model
model = nn.Sequential(
    nn.Linear(X1_train.shape[1], 32),
    nn.Tanh(),
    nn.Linear(32,1)
)
#Define loss function
loss_fn = nn.MSELoss()
#Define optimizer
optimizer = optim.SGD(model.parameters(), lr = 0.001)

#Training loop
epochs = 5000
for epoch in range(epochs+1):
  model.train()
  for inputs, targets in train_loader:
    optimizer.zero_grad()
    train_pred = model(inputs)
    train_loss = loss_fn(train_pred.squeeze(), targets) #Squeeze helps? IDK what it actually does though
    train_loss.backward()
    optimizer.step()

  #Validation
  model.eval()
  with torch.no_grad():
    test_pred = model(X1_test_ten)
    test_loss = loss_fn(test_pred.squeeze(), Y1_test_ten)
    if epoch % 500 == 0:
      print(f'Epoch {epoch}/{epochs}, Training Loss: {train_loss.item()}, Validation Loss: {test_loss.item()}')

Epoch 0/5000, Training Loss: 0.5521591305732727, Validation Loss: 0.8272017240524292
Epoch 500/5000, Training Loss: 0.25787609815597534, Validation Loss: 0.37508153915405273
Epoch 1000/5000, Training Loss: 0.18576453626155853, Validation Loss: 0.37909191846847534
Epoch 1500/5000, Training Loss: 0.7811512351036072, Validation Loss: 0.3777357041835785
Epoch 2000/5000, Training Loss: 0.6221002340316772, Validation Loss: 0.3771185278892517
Epoch 2500/5000, Training Loss: 0.2671995759010315, Validation Loss: 0.3795633614063263
Epoch 3000/5000, Training Loss: 0.24835620820522308, Validation Loss: 0.3816632926464081
Epoch 3500/5000, Training Loss: 0.25598031282424927, Validation Loss: 0.38390618562698364
Epoch 4000/5000, Training Loss: 0.1489628553390503, Validation Loss: 0.38773244619369507
Epoch 4500/5000, Training Loss: 0.4316060245037079, Validation Loss: 0.3933790922164917
Epoch 5000/5000, Training Loss: 0.06114552170038223, Validation Loss: 0.3993437588214874


In [ ]:
#PROBLEM 1b
# Load the housing dataset
file_path = '/content/drive/My Drive/Courses/Intro-to-ML/Datasets/Housing.csv'
housing = pd.DataFrame(pd.read_csv(file_path))

In [ ]:
#Convert YES/NO to 1/0
varlist = ['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']

#Defining map function
def binary_map(x):
  return x.map({'yes': 1, 'no': 0})

#Applying the function to the housing list
housing[varlist] = housing[varlist].apply(binary_map)

#Ignore furnishing status
housing = housing.drop('furnishingstatus', axis=1)

#Extract output
Y1 = housing['price'].values

#Extract inputs
housing = housing.drop('price', axis=1)
X1 = housing.values

#Split the dataset
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1,Y1, test_size = 0.8, random_state = 0)

#Input standardization
sc = StandardScaler()
X1_train = sc.fit_transform(X1_train)
X1_test = sc.transform(X1_test)

#Ouptut standardization
Y1_train = sc.fit_transform(Y1_train.reshape(-1,1)).flatten()
Y1_test = sc.fit_transform(Y1_test.reshape(-1,1)).flatten()

#Conver to tensors
X1_train_ten = torch.tensor(X1_train, dtype=torch.float32)
X1_test_ten = torch.tensor(X1_test, dtype=torch.float32)
Y1_train_ten = torch.tensor(Y1_train, dtype=torch.float32)
Y1_test_ten = torch.tensor(Y1_test, dtype=torch.float32)

#Dataloader for training and test sets
train_dataset = TensorDataset(X1_train_ten, Y1_train_ten)
train_loader = DataLoader(train_dataset, batch_size = 32, shuffle=True) #Using help

test_dataset = TensorDataset(X1_test_ten, Y1_test_ten)
test_loader = DataLoader(test_dataset, batch_size = 32)

In [ ]:
#Define model
model = nn.Sequential(
    nn.Linear(X1_train.shape[1], 32), #First layer 32
    nn.Tanh(),
    nn.Linear(32,64), #Second layer 64
    nn.Tanh(),
    nn.Linear(64,16), #Third layer 16
    nn.Tanh(),
    nn.Linear(16,1) #Output layer 1
)
#Define loss function
loss_fn = nn.MSELoss()
#Define optimizer
optimizer = optim.SGD(model.parameters(), lr = 0.001)

#Training loop
epochs = 5000
for epoch in range(epochs+1):
  model.train()
  for inputs, targets in train_loader:
    optimizer.zero_grad()
    train_pred = model(inputs)
    train_loss = loss_fn(train_pred.squeeze(), targets) #Squeeze helps?
    train_loss.backward()
    optimizer.step()

  #Validation
  model.eval()
  with torch.no_grad():
    test_pred = model(X1_test_ten)
    test_loss = loss_fn(test_pred.squeeze(), Y1_test_ten)
    if epoch % 500 == 0:
      print(f'Epoch {epoch}/{epochs}, Training Loss: {train_loss.item()}, Validation Loss: {test_loss.item()}')

Epoch 0/5000, Training Loss: 0.3941303491592407, Validation Loss: 1.1282501220703125
Epoch 500/5000, Training Loss: 0.3406645655632019, Validation Loss: 0.37599048018455505
Epoch 1000/5000, Training Loss: 0.17578209936618805, Validation Loss: 0.37180233001708984
Epoch 1500/5000, Training Loss: 0.7766872644424438, Validation Loss: 0.3705099821090698
Epoch 2000/5000, Training Loss: 0.48013317584991455, Validation Loss: 0.3680397570133209
Epoch 2500/5000, Training Loss: 0.30304238200187683, Validation Loss: 0.36355477571487427
Epoch 3000/5000, Training Loss: 0.12802955508232117, Validation Loss: 0.3605302572250366
Epoch 3500/5000, Training Loss: 0.10169292241334915, Validation Loss: 0.35728591680526733
Epoch 4000/5000, Training Loss: 0.1357458382844925, Validation Loss: 0.35606878995895386
Epoch 4500/5000, Training Loss: 0.6241586208343506, Validation Loss: 0.3575100004673004
Epoch 5000/5000, Training Loss: 0.07905048877000809, Validation Loss: 0.36221617460250854


In [9]:
#PROBLEM 2a
#Use CIFAR-10 dataset
train_data = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transforms.ToTensor())

#Determine mean and standard deviation
img = torch.stack([img_t for img_t, _ in train_data], dim=3)
mean = img.view(3,-1).mean(dim=1)
std_dev = img.view(3,-1).std(dim=1)

#Try to use GPU to speed up training
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

#Normalization transformation definition
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean,std_dev)
])

#Normalize dataset
train_data = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
train_loader = torch.utils.data.DataLoader(train_data, batch_size = 64, shuffle=True) #Batch size recommended
test_data = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
test_loader = torch.utils.data.DataLoader(test_data, batch_size=64, shuffle=False) #Batch size recommended

Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified


In [10]:
#Model definition, 1 hidden layer size 512
model = nn.Sequential(
    nn.Flatten(),
    nn.Linear(3072, 512), #32*32*3=3072
    nn.Tanh(),
    nn.Linear(512,10) #10 classes
).to(device) #GPU

#Loss/optimizer definition
loss_fn = nn.CrossEntropyLoss() #Recommended by friend, seems to give better results than NLLLoss
optimizer = optim.SGD(model.parameters(), lr=0.001) #SGD usually works best, lr can be changed if needed

In [11]:
#Training loop
epochs = 300 #300 required for 2b, so 300 for 2a seems reasonable, change if necessary
sum_start_time = time.time() #For training duration
for epoch in range(epochs):
  start_time = time.time()
  loss_over_time = 0.0
  for inputs, labels, in train_loader:
    inputs, labels = inputs.to(device), labels.to(device)

    optimizer.zero_grad()
    pred = model(inputs)
    loss = loss_fn(pred, labels)
    loss.backward()
    optimizer.step()
    loss_over_time += loss.item()


  #Test
  model.eval()
  pred_correct = 0
  pred_total = 0
  with torch.no_grad(): #No learning form test
    for inputs, labels in test_loader:
      inputs, labels = inputs.to(device), labels.to(device)
      pred = model(inputs)
      _, predicted = torch.max(pred.data, 1)
      pred_total += labels.size(0)
      pred_correct += (predicted == labels).sum().item()
  pred_accuracy = pred_correct/pred_total
  model.train()

  #Training duration
  final_time = time.time()
  train_time = final_time - start_time

  #Display info:
  #Epoch/loss
  if epoch % 10 == 0:
    print(f'Epoch: {epoch+1}/{epochs}, Loss: {loss_over_time/len(train_loader)}, Training Time: {train_time:.2f} seconds')
  #Time
  sum_end_time = time.time()
  sum_train_time = sum_end_time - sum_start_time
  print(f'Total Training Time: {sum_train_time:.2f} seconds')
  #Accuracy
  print(f'Test Accuracy: {pred_accuracy * 100:.2f}%')

#Final Accuracy after training
print(f'Final Test Accuracy: {pred_accuracy * 100:.2f}%')

Epoch: 1/300, Loss: 2.009564500635542, Training Time: 28.19 seconds
Total Training Time: 28.20 seconds
Test Accuracy: 34.86%
Total Training Time: 58.06 seconds
Test Accuracy: 37.04%
Total Training Time: 87.87 seconds
Test Accuracy: 38.16%
Total Training Time: 116.32 seconds
Test Accuracy: 39.01%
Total Training Time: 145.23 seconds
Test Accuracy: 39.42%
Total Training Time: 175.05 seconds
Test Accuracy: 39.54%
Total Training Time: 204.20 seconds
Test Accuracy: 40.28%
Total Training Time: 232.39 seconds
Test Accuracy: 40.69%
Total Training Time: 262.13 seconds
Test Accuracy: 41.16%
Total Training Time: 292.05 seconds
Test Accuracy: 41.25%
Epoch: 11/300, Loss: 1.699547638826053, Training Time: 27.72 seconds
Total Training Time: 319.77 seconds
Test Accuracy: 41.55%
Total Training Time: 349.30 seconds
Test Accuracy: 41.70%
Total Training Time: 379.05 seconds
Test Accuracy: 42.17%
Total Training Time: 407.37 seconds
Test Accuracy: 41.86%
Total Training Time: 436.29 seconds
Test Accuracy: 42.

In [13]:
#PROBLEM 2b
#Use CIFAR-10 dataset
train_data = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transforms.ToTensor())

#Determine mean and standard deviation
img = torch.stack([img_t for img_t, _ in train_data], dim=3)
mean = img.view(3,-1).mean(dim=1)
std_dev = img.view(3,-1).std(dim=1)

#Try to use GPU to speed up training
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

#Normalization transformation definition
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean,std_dev)
])

#Normalize dataset
train_data = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
train_loader = torch.utils.data.DataLoader(train_data, batch_size = 64, shuffle=True) #Batch size recommended
test_data = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
test_loader = torch.utils.data.DataLoader(test_data, batch_size=64, shuffle=False) #Batch size recommended

Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified


In [16]:
#Model definition, 1 hidden layer size 512
model = nn.Sequential(
    nn.Flatten(),
    nn.Linear(3072, 512), #32*32*3=3072
    nn.ReLU(),  #Better results than tanh
    nn.Linear(512,128),
    nn.ReLU(),
    nn.Linear(128,64),
    nn.ReLU(),
    nn.Linear(64,10) #10 classes
).to(device) #GPU

#Loss/optimizer definition
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.001) #SGD usually works best, lr can be changed if needed

In [17]:
#Training loop
epochs = 300 #300 required for 2b
sum_start_time = time.time() #For training duration
for epoch in range(epochs):
  start_time = time.time()
  loss_over_time = 0.0
  for inputs, labels, in train_loader:
    inputs, labels = inputs.to(device), labels.to(device)

    optimizer.zero_grad()
    pred = model(inputs)
    loss = loss_fn(pred, labels)
    loss.backward()
    optimizer.step()
    loss_over_time += loss.item()


  #Test
  model.eval()
  pred_correct = 0
  pred_total = 0
  #For confusion matrix
  cf_predicted = []
  cf_labels = []
  with torch.no_grad(): #No learning form test
    for inputs, labels in test_loader:
      inputs, labels = inputs.to(device), labels.to(device)
      pred = model(inputs)
      _, predicted = torch.max(pred.data, 1)
      pred_total += labels.size(0)
      pred_correct += (predicted == labels).sum().item()
      cf_predicted.extend(predicted.cpu().numpy()) #Help says this will allow for confusion matrix
      cf_labels.extend(labels.cpu().numpy())  #Help says this will allow for confusion matrix
  pred_accuracy = pred_correct/pred_total
  model.train()

  #Training duration
  final_time = time.time()
  train_time = final_time - start_time

  #Display info:
  #Epoch/loss
  if epoch % 10 == 0:
    print(f'Epoch: {epoch+1}/{epochs}, Loss: {loss_over_time/len(train_loader)}, Training Time: {train_time:.2f} seconds')
  #Time
  sum_end_time = time.time()
  sum_train_time = sum_end_time - sum_start_time
  print(f'Total Training Time: {sum_train_time:.2f} seconds')
  #Accuracy
  print(f'Test Accuracy: {pred_accuracy * 100:.2f}%')

#Final Accuracy after training
print(f'Final Test Accuracy: {pred_accuracy * 100:.2f}%')



Epoch: 1/300, Loss: 2.294490202918382, Training Time: 29.28 seconds
Total Training Time: 29.28 seconds
Test Accuracy: 19.80%
Total Training Time: 57.35 seconds
Test Accuracy: 22.79%
Total Training Time: 85.16 seconds
Test Accuracy: 22.17%
Total Training Time: 114.71 seconds
Test Accuracy: 24.07%
Total Training Time: 144.56 seconds
Test Accuracy: 27.90%
Total Training Time: 173.63 seconds
Test Accuracy: 30.21%
Total Training Time: 204.05 seconds
Test Accuracy: 31.50%
Total Training Time: 234.80 seconds
Test Accuracy: 33.13%
Total Training Time: 265.28 seconds
Test Accuracy: 34.72%
Total Training Time: 294.49 seconds
Test Accuracy: 35.55%
Epoch: 11/300, Loss: 1.8095696970934758, Training Time: 30.18 seconds
Total Training Time: 324.67 seconds
Test Accuracy: 36.54%
Total Training Time: 354.91 seconds
Test Accuracy: 37.64%
Total Training Time: 387.52 seconds
Test Accuracy: 38.20%
Total Training Time: 416.84 seconds
Test Accuracy: 39.16%
Total Training Time: 446.60 seconds
Test Accuracy: 39

In [18]:
#Confusion matrix
cm = confusion_matrix(cf_labels,cf_predicted)
print('Trained Model - Confusion Matrix')
print(cm)

Trained Model - Confusion Matrix
[[598  34  72  31  39  14  20  20 109  63]
 [ 57 580  14  39  13   7  22  20  55 193]
 [ 83  10 410 100 139  93  75  45  28  17]
 [ 28   9 115 369  76 190  89  56  25  43]
 [ 50   6 134  86 434  51  87 103  25  24]
 [ 20   5  90 226  63 414  42  85  22  33]
 [ 18  20  87 130 112  55 527  15  15  21]
 [ 43   4  60  69  92 108  12 542   5  65]
 [ 95  71  20  42  33  14  16  15 641  53]
 [ 65 150  15  59  19  21  23  41  55 552]]
